(()=>{"use strict";
const STORE="birthday-calendar-ru-v1",LANG="birthday-calendar-lang",relationKeys=["family","friend","colleague","partner","other"],icons={family:"👨‍👩‍👧‍👦",friend:"🤝",colleague:"💼",partner:"❤️",other:"👤"},legacy={"Семья":"family","Друг":"friend","Коллега":"colleague","Партнёр":"partner","Другое":"other","Familie":"family","Prieten":"friend","Coleg":"colleague","Partener":"partner","Altă relație":"other"};
let items=[],lang=localStorage.getItem(LANG)==="ro"?"ro":"ru",relation="family";const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)],esc=s=>String(s||"").replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[c]));
try{items=JSON.parse(localStorage.getItem(STORE)||"[]")}catch{items=[]}
const tr=()=>I18N[lang],key=v=>legacy[v]||v;
function parts(v){const[y,m,d]=v.split("-").map(Number);return{y,m,d}}
function info(v){const{y,m,d}=parts(v),now=new Date(),today=new Date(now.getFullYear(),now.getMonth(),now.getDate());let next=new Date(now.getFullYear(),m-1,d);if(next<today)next=new Date(now.getFullYear()+1,m-1,d);return{days:Math.round((next-today)/86400000),age:next.getFullYear()-y}}
function dateText(v){const{y,m,d}=parts(v);return new Intl.DateTimeFormat(lang==="ru"?"ru-RU":"ro-RO",{day:"2-digit",month:"long",year:"numeric"}).format(new Date(y,m-1,d))}
function dayText(days){const t=tr();if(days===0)return t.todayLabel;if(days===1)return t.tomorrow;let n;if(lang==="ro")n=days===1?t.day1:t.day2;else{const a=days%10,b=days%100;n=a===1&&b!==11?t.day1:a>=2&&a<=4&&!(b>=12&&b<=14)?t.day2:t.day5}return`${t.inPrefix} ${days} ${n}`}
function save(){localStorage.setItem(STORE,JSON.stringify(items))}
function translate(){const t=tr();document.documentElement.lang=lang;document.title=lang==="ru"?"Календарь дней рождения":"Calendarul zilelor de naștere";$$("[data-i18n]").forEach(el=>el.textContent=t[el.dataset.i18n]);$$("[data-i18n-placeholder]").forEach(el=>el.placeholder=t[el.dataset.i18nPlaceholder]);$("#languageSlider").className=`language-slider ${lang}`;$$("[data-lang]").forEach(b=>b.classList.toggle("active",b.dataset.lang===lang));renderRelations();render()}
function renderRelations(){$("#relationGrid").innerHTML=relationKeys.map(k=>`<button type="button" data-relation="${k}" class="${relation===k?"selected":""}"><span>${icons[k]}</span>${tr().relations[k]}</button>`).join("");$$("[data-relation]").forEach(b=>b.onclick=()=>{relation=b.dataset.relation;renderRelations()})}
function render(){const t=tr(),q=$("#searchInput").value.toLowerCase(),sorted=[...items].filter(x=>x.name.toLowerCase().includes(q)).sort((a,b)=>info(a.date).days-info(b.date).days),today=sorted.filter(x=>info(x.date).days===0),month=sorted.filter(x=>parts(x.date).m===new Date().getMonth()+1);$("#totalCount").textContent=items.length;$("#monthCount").textContent=month.length;$("#todayCount").textContent=today.length;$("#addAllCalendar").disabled=!items.length;$("#listCount").hidden=items.length<=3;$("#listCount").textContent=items.length;$("#searchBox").hidden=items.length<=3;
const nearest=sorted[0];$("#hero").innerHTML=nearest?`<section class="spotlight liquid"><div class="spotlight-top"><span>✦ ${t.nearest}</span><b>${dayText(info(nearest.date).days)}</b></div><div class="spotlight-main"><div class="avatar">${esc(nearest.name.slice(0,1).toUpperCase())}</div><div class="spotlight-copy"><h2>${esc(nearest.name)}</h2><p>🎂 ${dateText(nearest.date)} · ${info(nearest.date).age} ${t.years}</p></div><div class="age-ring"><strong>${info(nearest.date).age}</strong><small>${t.years}</small></div></div></section>`:`<section class="empty-hero liquid"><div class="gift">🎁</div><h2>${t.emptyTitle}</h2><p>${t.emptyText}</p><button id="emptyAdd">＋ ${t.add}</button></section>`;
if(!nearest)$("#emptyAdd").onclick=openDialog;
$("#birthdayList").innerHTML=sorted.map(x=>{const i=info(x.date),k=key(x.relation),rel=t.relations[k]||x.relation;return`<article class="birthday-row liquid ${i.days===0?"today":""}"><div class="mini-avatar">${icons[k]||"👤"}</div><div class="person"><h3>${esc(x.name)}</h3><p>🎂 ${dateText(x.date)} · ${i.age} ${t.years}</p><span>${esc(rel)}${x.note?` · ${esc(x.note)}`:""}</span></div><div class="when"><b>${dayText(i.days)}</b><div class="row-actions"><button data-cal="${x.id}" aria-label="Calendar">▣＋</button><button data-del="${x.id}" aria-label="Delete">⌫</button></div></div></article>`}).join("");
$$("[data-cal]").forEach(b=>b.onclick=()=>downloadCalendar(items.filter(x=>x.id===b.dataset.cal)));$$("[data-del]").forEach(b=>b.onclick=()=>{if(confirm(t.deleteAsk)){items=items.filter(x=>x.id!==b.dataset.del);save();render()}})}
function openDialog(){$("#birthdayDialog").showModal();setTimeout(()=>$("#personName").focus(),50)}
function icsEsc(v){return String(v||"").replace(/\\/g,"\\\\").replace(/\n/g,"\\n").replace(/,/g,"\\,").replace(/;/g,"\\;")}
function event(x){const t=tr(),{y,m,d}=parts(x.date),start=`${y}${String(m).padStart(2,"0")}${String(d).padStart(2,"0")}`,tomorrow=new Date(y,m-1,d+1),end=`${tomorrow.getFullYear()}${String(tomorrow.getMonth()+1).padStart(2,"0")}${String(tomorrow.getDate()).padStart(2,"0")}`,rel=t.relations[key(x.relation)]||x.relation;return["BEGIN:VEVENT",`UID:birthday-${x.id}@birthday-calendar`,`DTSTART;VALUE=DATE:${start}`,`DTEND;VALUE=DATE:${end}`,"RRULE:FREQ=YEARLY",`SUMMARY:${icsEsc(`🎂 ${t.birthdayFor} — ${x.name}`)}`,`DESCRIPTION:${icsEsc([rel,x.note].filter(Boolean).join(" · "))}`,"BEGIN:VALARM","TRIGGER:-P7D","ACTION:DISPLAY",`DESCRIPTION:${icsEsc(`${t.weekAlert} — ${x.name}`)}`,"END:VALARM","BEGIN:VALARM","TRIGGER:-P1D","ACTION:DISPLAY",`DESCRIPTION:${icsEsc(`${t.dayAlert} — ${x.name}`)}`,"END:VALARM","END:VEVENT"].join("\r\n")}
function downloadCalendar(list){if(!list.length)return;const body=["BEGIN:VCALENDAR","VERSION:2.0","PRODID:-//Birthday Calendar//RO-RU","CALSCALE:GREGORIAN","METHOD:PUBLISH",...list.map(event),"END:VCALENDAR"].join("\r\n"),url=URL.createObjectURL(new Blob([body],{type:"text/calendar;charset=utf-8"})),a=document.createElement("a");a.href=url;a.download=list.length===1?`birthday-${list[0].name}.ics`:"birthdays.ics";a.click();setTimeout(()=>URL.revokeObjectURL(url),1000)}
$$("[data-lang]").forEach(b=>b.onclick=()=>{lang=b.dataset.lang;localStorage.setItem(LANG,lang);translate()});$("#openAdd").onclick=openDialog;$("#searchInput").oninput=render;$("#addAllCalendar").onclick=()=>downloadCalendar(items);$("#birthdayForm").onsubmit=e=>{e.preventDefault();const name=$("#personName").value.trim(),date=$("#personDate").value;if(!name||!date)return;items.push({id:crypto.randomUUID(),name,date,relation,note:$("#personNote").value.trim()});save();e.target.reset();relation="family";$("#birthdayDialog").close();translate()};translate();
})();