(()=>{"use strict";
const STORE="birthday-calendar-ru-v2",OLD_STORE="birthday-calendar-ru-v1",PREFS="birthday-calendar-prefs-v2",PROFILE="birthday-calendar-profile-v2",GUEST="birthday-calendar-guest-v1";
const relationKeys=["family","friend","colleague","partner","other"],icons={family:"👨‍👩‍👧‍👦",friend:"🤝",colleague:"💼",partner:"♥",other:"👤"},legacy={"Семья":"family","Друг":"friend","Коллега":"colleague","Партнёр":"partner","Другое":"other","Familie":"family","Prieten":"friend","Coleg":"colleague","Partener":"partner","Altă relație":"other"};
const eventTypes=["birthday","anniversary","nameDay","important"],giftStatuses=["idea","chosen","ordered","wrapped","given"];
const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)],esc=s=>String(s??"").replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[c]));
function keepDialogCloseVisible(dialog){const close=dialog.querySelector(".dialog-close");if(close)close.style.transform=`translateY(${dialog.scrollTop}px)`}
$$('.app-dialog').forEach(dialog=>dialog.addEventListener("scroll",()=>keepDialogCloseVisible(dialog),{passive:true}));
const read=(key,fallback)=>{try{return JSON.parse(localStorage.getItem(key))??fallback}catch{return fallback}};
let items=read(STORE,read(OLD_STORE,[])),prefs={lang:"ro",theme:"auto",...read(PREFS,{})},profile=read(PROFILE,null),relation="family",filter="all",messagePerson=null,messageTone="warm",pendingPhoto="";
const normalizeItem=x=>({...x,relation:legacy[x.relation]||x.relation||"other",eventType:eventTypes.includes(x.eventType)?x.eventType:"birthday",giftStatus:giftStatuses.includes(x.giftStatus)?x.giftStatus:"idea",giftHistory:Array.isArray(x.giftHistory)?x.giftHistory:[]});
items=Array.isArray(items)?items.map(normalizeItem):[];
const queryParams=new URLSearchParams(location.search),shareParam=queryParams.get("share"),wishlistParam=queryParams.get("wishlist"),isPublicView=!!shareParam;
let currentUser=null,authMode="login",cloudTimer=null;
const tr=()=>I18N[prefs.lang],saveItems=()=>{localStorage.setItem(STORE,JSON.stringify(items));queueCloudSave()},savePrefs=()=>localStorage.setItem(PREFS,JSON.stringify(prefs));
function publicPayload(){return{public:true,name:profile?.name||"",currency:profile?.currency||"MDL",items:items.map(({phone,wishlist,giftHistory,...rest})=>rest)}}
function queueCloudSave(){if(!currentUser||isPublicView)return;clearTimeout(cloudTimer);cloudTimer=setTimeout(()=>{const jobs=[AppCloud.saveUserData(currentUser.uid,{profile,prefs,items})];if(profile?.mode==="public")jobs.push(AppCloud.setPublicShare(currentUser.uid,publicPayload()));Promise.all(jobs).catch(error=>console.warn("Cloud save failed",error))},700)}
function parts(v){const[y,m,d]=String(v).split("-").map(Number);return{y,m,d}}
function birthdayInfo(v){const{y,m,d}=parts(v),now=new Date(),today=new Date(now.getFullYear(),now.getMonth(),now.getDate());let next=new Date(now.getFullYear(),m-1,d);if(next<today)next=new Date(now.getFullYear()+1,m-1,d);return{days:Math.round((next-today)/86400000),age:next.getFullYear()-y,next}}
function dateText(v,year=true){const{y,m,d}=parts(v);return new Intl.DateTimeFormat(prefs.lang==="ru"?"ru-RU":"ro-RO",{day:"numeric",month:"long",...(year?{year:"numeric"}:{})}).format(new Date(y,m-1,d))}
const zodiacSigns=[
  {key:"capricorn",symbol:"♑",from:1222,to:1231},{key:"capricorn",symbol:"♑",from:101,to:119},
  {key:"aquarius",symbol:"♒",from:120,to:218},{key:"pisces",symbol:"♓",from:219,to:320},
  {key:"aries",symbol:"♈",from:321,to:419},{key:"taurus",symbol:"♉",from:420,to:520},
  {key:"gemini",symbol:"♊",from:521,to:620},{key:"cancer",symbol:"♋",from:621,to:722},
  {key:"leo",symbol:"♌",from:723,to:822},{key:"virgo",symbol:"♍",from:823,to:922},
  {key:"libra",symbol:"♎",from:923,to:1022},{key:"scorpio",symbol:"♏",from:1023,to:1121},
  {key:"sagittarius",symbol:"♐",from:1122,to:1221}
];
function zodiacInfo(date){const{m,d}=parts(date),value=m*100+d;return zodiacSigns.find(sign=>value>=sign.from&&value<=sign.to)||null}
function zodiacText(date){const sign=zodiacInfo(date);return sign?`${sign.symbol} ${tr().zodiacSigns?.[sign.key]||sign.key}`:""}
function updateZodiacField(){const field=$("#personZodiac");if(field)field.value=zodiacText($("#personDate").value)}
function dayText(days){const t=tr();if(days===0)return t.todayLabel;if(days===1)return t.tomorrow;let n=t.day2;if(prefs.lang==="ru"){const a=days%10,b=days%100;n=a===1&&b!==11?t.day1:a>=2&&a<=4&&!(b>=12&&b<=14)?t.day2:t.day5}return`${t.inPrefix} ${days} ${n}`}
function formatMoney(n){return new Intl.NumberFormat(prefs.lang==="ru"?"ru-RU":"ro-RO",{style:"currency",currency:profile?.currency||"MDL",maximumFractionDigits:0}).format(Number(n)||0)}
function avatar(x,cls="mini-avatar"){return`<div class="${cls}">${x.photo?`<img src="${x.photo}" alt="">`:esc((x.name||"?").slice(0,1).toUpperCase())}</div>`}
function toast(text){const el=$("#toast");el.textContent=text;el.classList.add("show");clearTimeout(toast.timer);toast.timer=setTimeout(()=>el.classList.remove("show"),2200)}
function applyTheme(){const value=prefs.theme==="auto"?(matchMedia("(prefers-color-scheme: light)").matches?"light":"dark"):prefs.theme;document.documentElement.dataset.theme=value;$("meta[name=theme-color]").content="#1b1917"}
function translate(){const t=tr();document.documentElement.lang=prefs.lang;document.title=prefs.lang==="ru"?"Календарь дней рождения":"Calendarul aniversărilor";$$('[data-i18n]').forEach(el=>{if(t[el.dataset.i18n]!=null)el.textContent=t[el.dataset.i18n]});$$('[data-i18n-placeholder]').forEach(el=>el.placeholder=t[el.dataset.i18nPlaceholder]||"");$$('[data-i18n-title]').forEach(el=>el.title=t[el.dataset.i18nTitle]||"");$("#languageSlider").classList.toggle("ru",prefs.lang==="ru");$$('[data-lang]').forEach(b=>b.classList.toggle("active",b.dataset.lang===prefs.lang));renderRelations();renderFilters();updateProfileUI();renderAll()}
function renderRelations(){$("#relationGrid").innerHTML=relationKeys.map(k=>`<button type="button" data-relation="${k}" class="${relation===k?"selected":""}"><span>${icons[k]}</span>${tr().relations[k]}</button>`).join("");$$('[data-relation]').forEach(b=>b.onclick=()=>{relation=b.dataset.relation;renderRelations()})}
function renderFilters(){const t=tr(),filters=[["all",t.all],["month",t.thisMonth],["soon",t.next30],...relationKeys.map(k=>[k,`${icons[k]} ${t.relations[k]}`])];$("#filterRow").innerHTML=filters.map(([k,label])=>`<button class="${filter===k?"active":""}" data-filter="${k}">${label}</button>`).join("");$$('[data-filter]').forEach(b=>b.onclick=()=>{filter=b.dataset.filter;renderFilters();renderList()})}
function filteredItems(){const q=$("#searchInput").value.trim().toLocaleLowerCase(),month=new Date().getMonth()+1;return [...items].filter(x=>!q||[x.name,x.note,x.interests,x.gift].some(v=>String(v||"").toLocaleLowerCase().includes(q))).filter(x=>filter==="all"||filter==="month"&&parts(x.date).m===month||filter==="soon"&&birthdayInfo(x.date).days<=30||relationKeys.includes(filter)&&x.relation===filter).sort((a,b)=>birthdayInfo(a.date).days-birthdayInfo(b.date).days)}
function emptyBlock(title,text,button=false){return`<div class="empty-state liquid"><div class="empty-icon">🎁</div><h3>${title}</h3><p>${text}</p>${button?`<button data-empty-add>＋ ${tr().add}</button>`:""}</div>`}
function renderStats(){const now=new Date(),month=now.getMonth()+1,soon=items.filter(x=>birthdayInfo(x.date).days<=30).length,budget=items.reduce((s,x)=>s+(Number(x.budget)||0),0);$("#totalCount").textContent=items.length;$("#monthCount").textContent=items.filter(x=>parts(x.date).m===month).length;$("#soonCount").textContent=soon;$("#budgetCount").textContent=budget?new Intl.NumberFormat(prefs.lang==="ru"?"ru-RU":"ro-RO",{notation:"compact",maximumFractionDigits:1}).format(budget):"0";$("#addAllCalendar").disabled=!items.length;$("#listCount").textContent=items.length;if("setAppBadge" in navigator){items.filter(x=>birthdayInfo(x.date).days<=7).length?navigator.setAppBadge(soon).catch(()=>{}):navigator.clearAppBadge().catch(()=>{})}}
function eventLabel(x){return tr().eventTypes?.[x.eventType]||tr().eventTypes?.birthday||"Aniversare"}
function renderSpotlight(){const x=[...items].sort((a,b)=>birthdayInfo(a.date).days-birthdayInfo(b.date).days)[0],t=tr();if(!x){$("#spotlight").innerHTML=emptyBlock(t.emptyTitle,t.emptyText,true);$('[data-empty-add]')?.addEventListener("click",()=>openPerson());return}const i=birthdayInfo(x.date),birthday=x.eventType==="birthday";$("#spotlight").innerHTML=`<article class="spotlight liquid"><div class="spotlight-top"><span>✦ ${t.nearest}</span><b>${dayText(i.days)}</b></div><div class="spotlight-main">${avatar(x,"avatar")}<div class="spotlight-copy"><h2>${esc(x.name)}</h2><p>${birthday?"🎂":"✦"} ${eventLabel(x)} · ${dateText(x.date)}${birthday?` · ${t.turns} ${i.age} ${t.years} · ${zodiacText(x.date)}`:""}</p><div class="spotlight-actions"><button data-msg="${x.id}">✨ ${t.message}</button><button data-cal="${x.id}">▣ ${t.calendarAction}</button><button data-edit="${x.id}">✎ ${t.edit}</button></div></div>${birthday?`<div class="age-ring"><strong>${i.age}</strong><small>${t.years}</small></div>`:""}</div></article>`;bindItemActions($("#spotlight"))}
function renderList(){const list=filteredItems(),t=tr();$("#birthdayList").innerHTML=list.length?list.map(x=>{const i=birthdayInfo(x.date),rel=t.relations[x.relation]||x.relation,birthday=x.eventType==="birthday";return`<article class="birthday-row liquid ${i.days===0?"today":""}">${avatar(x)}<div class="person"><h3>${esc(x.name)}</h3><p>${birthday?"🎂":"✦"} ${eventLabel(x)} · ${dateText(x.date,false)}${birthday?` · ${i.age} ${t.years} · ${zodiacText(x.date)}`:""}</p><span>${esc(rel)}${x.interests?` · ${esc(x.interests)}`:""}</span></div><div class="when"><b>${dayText(i.days)}</b><div class="row-actions"><button data-msg="${x.id}" title="${t.message}">✨</button><button data-cal="${x.id}" title="${t.calendarAction}">▣＋</button><button data-edit="${x.id}" title="${t.edit}">✎</button><button class="delete" data-del="${x.id}" title="${t.delete}">⌫</button></div></div></article>`}).join(""):emptyBlock(t.emptyTitle,t.emptyText,items.length===0);bindItemActions($("#birthdayList"));$('[data-empty-add]')?.addEventListener("click",()=>openPerson())}
function renderYear(){const t=tr();$("#yearGrid").innerHTML=t.months.map((name,index)=>{const list=items.filter(x=>parts(x.date).m===index+1).sort((a,b)=>parts(a.date).d-parts(b.date).d);return`<article class="month-card liquid"><header><h3>${name}</h3><span>${list.length}</span></header>${list.length?list.map(x=>`<div class="month-person"><b>${String(parts(x.date).d).padStart(2,"0")}</b><span>${esc(x.name)}</span></div>`).join(""):`<p class="month-empty">${t.emptyYear}</p>`}</article>`}).join("")}
function suggestedGift(x){if(x.gift)return x.gift;const s=String(x.interests||"").toLowerCase(),ru=prefs.lang==="ru";if(/cafe|coffee|коф/.test(s))return ru?"Подарочный набор кофе или термокружка":"Set de cafea sau cană termo";if(/carte|book|книг/.test(s))return ru?"Книга или сертификат книжного магазина":"Carte sau voucher la librărie";if(/travel|călător|путеше/.test(s))return ru?"Дорожный органайзер или впечатление":"Organizator de călătorie sau experiență";if(/sport|fitness|спорт/.test(s))return ru?"Спортивный аксессуар или абонемент":"Accesoriu sportiv sau abonament";if(/beauty|frumuse|космет/.test(s))return ru?"Набор ухода или сертификат SPA":"Set de îngrijire sau voucher SPA";return ru?"Персональный подарок по интересам":"Cadou personalizat după interese"}
function renderGifts(){const t=tr(),list=items.filter(x=>x.gift||x.interests||Number(x.budget));$("#giftBudgetTotal").textContent=formatMoney(items.reduce((s,x)=>s+(Number(x.budget)||0),0));$("#giftList").innerHTML=list.length?list.sort((a,b)=>birthdayInfo(a.date).days-birthdayInfo(b.date).days).map(x=>`<article class="gift-row liquid"><span class="gift-icon">🎁</span><div class="gift-copy"><h3>${esc(x.name)}</h3><p>${esc(suggestedGift(x))}</p>${x.interests?`<p>♡ ${esc(x.interests)}</p>`:""}<div class="gift-tools"><select data-gift-status="${x.id}" aria-label="${t.giftProgress||"Progres"}">${giftStatuses.map(s=>`<option value="${s}" ${x.giftStatus===s?"selected":""}>${t.giftStatuses?.[s]||s}</option>`).join("")}</select><button class="ai-gift-button" type="button" data-ai-gift="${x.id}">✦ ${t.aiGiftButton||"Sfaturi AI"}</button><button class="history-button" type="button" data-gift-history="${x.id}">↺ ${t.giftHistory||"Istoric"}</button></div></div><strong>${x.budget?formatMoney(x.budget):""}</strong></article>`).join(""):emptyBlock(t.emptyGifts,"",false);$$('[data-gift-status]').forEach(s=>s.onchange=()=>updateItem(s.dataset.giftStatus,{giftStatus:s.value}))}
function renderAll(){renderStats();renderSpotlight();renderList();renderYear();renderGifts()}
function bindItemActions(root){root.querySelectorAll('[data-edit]').forEach(b=>b.onclick=()=>openPerson(items.find(x=>x.id===b.dataset.edit)));root.querySelectorAll('[data-msg]').forEach(b=>b.onclick=()=>openMessage(items.find(x=>x.id===b.dataset.msg)));root.querySelectorAll('[data-cal]').forEach(b=>b.onclick=()=>downloadCalendar(items.filter(x=>x.id===b.dataset.cal)));root.querySelectorAll('[data-del]').forEach(b=>b.onclick=()=>{if(confirm(tr().deleteAsk)){items=items.filter(x=>x.id!==b.dataset.del);saveItems();renderAll();toast(tr().deleted)}})}
function openPerson(x=null){const t=tr(),form=$("#birthdayForm");form.reset();relation=x?.relation||"family";pendingPhoto=x?.photo||"";$("#personId").value=x?.id||"";$("#personName").value=x?.name||"";$("#personDate").value=x?.date||"";$("#personPhone").value=x?.phone||"";$("#personInterests").value=x?.interests||"";$("#personGift").value=x?.gift||"";$("#personBudget").value=x?.budget||"";$("#personNote").value=x?.note||"";$("#personEventType").value=x?.eventType||"birthday";$("#personPersonality").value=x?.personality||"";$("#personStyle").value=x?.style||"";$("#personWishlist").value=x?.wishlist||"";$("#birthdayDialogTitle").textContent=x?t.editTitle:t.addTitle;updateZodiacField();renderRelations();renderPhoto();$("#birthdayDialog").showModal();setTimeout(()=>$("#personName").focus(),80)}
function renderPhoto(){$("#photoPreview").innerHTML=pendingPhoto?`<img src="${pendingPhoto}" alt="">`:"＋"}
function processPhoto(file){return new Promise((resolve,reject)=>{const reader=new FileReader();reader.onerror=reject;reader.onload=()=>{const img=new Image();img.onerror=reject;img.onload=()=>{const max=480,scale=Math.min(1,max/Math.max(img.width,img.height)),canvas=document.createElement("canvas");canvas.width=Math.round(img.width*scale);canvas.height=Math.round(img.height*scale);canvas.getContext("2d").drawImage(img,0,0,canvas.width,canvas.height);resolve(canvas.toDataURL("image/jpeg",.78))};img.src=reader.result};reader.readAsDataURL(file)})}
function openMessage(x){if(!x)return;messagePerson=x;messageTone="warm";$("#messageFor").textContent=x.name;$("#messageFor").dataset.personId=x.id;renderTones();$("#messageDialog").showModal()}
function renderTones(){const t=tr();$("#toneRow").innerHTML=Object.entries(t.tones).map(([k,v])=>`<button class="${messageTone===k?"active":""}" data-tone="${k}">${v}</button>`).join("");$("#greetingText").value=t.greetings[messageTone].replaceAll("{name}",messagePerson?.name||"");$$('[data-tone]').forEach(b=>b.onclick=()=>{messageTone=b.dataset.tone;renderTones()})}
function shareUrl(type){const text=encodeURIComponent($("#greetingText").value),phone=String(messagePerson?.phone||"").replace(/\D/g,"");if(type==="whatsapp"){if(!phone){toast(tr().noPhone);return}open(`https://wa.me/${phone}?text=${text}`,"_blank","noopener")}else open(`https://t.me/share/url?url=&text=${text}`,"_blank","noopener")}
function updateProfileUI(){const t=tr(),name=profile?.name||t.profileFallback;$("#profileName").textContent=name;$("#profileAvatar").textContent=name.slice(0,1).toUpperCase();$("#settingsProfileName").textContent=name;$("#ownerName").value=profile?.name||"";$("#ownerCurrency").value=profile?.currency||"MDL";$("#profileMode").value=profile?.mode||"private";updateModeHint();updateShareBox();updateAuthStatus()}
function updateModeHint(){$("#profileModeHint").textContent=$("#profileMode").value==="public"?tr().publicHint:tr().privateHint}
function updateShareBox(){const box=$("#shareBox");if(profile?.mode==="public"&&currentUser){$("#shareLinkInput").value=`${location.origin}${location.pathname}?share=${currentUser.uid}`;box.hidden=false}else box.hidden=true}
function updateAuthStatus(){const line=$("#authStatusLine"),signOut=$("#signOutButton");if(currentUser){line.textContent=`${tr().loggedInAs} ${currentUser.email}`;signOut.hidden=false}else{line.textContent=tr().notLoggedIn;signOut.hidden=true}}
function openProfile(){$("#settingsDialog").open&&$("#settingsDialog").close();updateProfileUI();$("#profileDialog").showModal()}
function icsEsc(v){return String(v||"").replace(/\\/g,"\\\\").replace(/\n/g,"\\n").replace(/,/g,"\\,").replace(/;/g,"\\;")}
function calendarEvent(x){const t=tr(),{y,m,d}=parts(x.date),start=`${y}${String(m).padStart(2,"0")}${String(d).padStart(2,"0")}`,endDate=new Date(y,m-1,d+1),end=`${endDate.getFullYear()}${String(endDate.getMonth()+1).padStart(2,"0")}${String(endDate.getDate()).padStart(2,"0")}`,rel=t.relations[x.relation]||x.relation;return["BEGIN:VEVENT",`UID:birthday-${x.id}@birthday-calendar`,`DTSTART;VALUE=DATE:${start}`,`DTEND;VALUE=DATE:${end}`,"RRULE:FREQ=YEARLY",`SUMMARY:${icsEsc(`${x.eventType==="birthday"?"🎂":"✦"} ${eventLabel(x)} — ${x.name}`)}`,`DESCRIPTION:${icsEsc([rel,x.note,x.gift?`🎁 ${x.gift}`:""].filter(Boolean).join(" · "))}`,...[["-P30D",t.alert30],["-P7D",t.weekAlert],["-P1D",t.dayAlert]].flatMap(([trigger,label])=>["BEGIN:VALARM",`TRIGGER:${trigger}`,"ACTION:DISPLAY",`DESCRIPTION:${icsEsc(`${label} — ${x.name}`)}`,"END:VALARM"]),"END:VEVENT"].join("\r\n")}
function downloadCalendar(list){if(!list.length)return;const body=["BEGIN:VCALENDAR","VERSION:2.0","PRODID:-//Birthday Calendar//RO-RU","CALSCALE:GREGORIAN","METHOD:PUBLISH",...list.map(calendarEvent),"END:VCALENDAR"].join("\r\n"),url=URL.createObjectURL(new Blob([body],{type:"text/calendar;charset=utf-8"})),a=document.createElement("a");a.href=url;a.download=list.length===1?`birthday-${list[0].name.replace(/\s+/g,"-")}.ics`:"birthdays.ics";a.click();setTimeout(()=>URL.revokeObjectURL(url),1000)}
function exportBackup(){const blob=new Blob([JSON.stringify({version:2,exportedAt:new Date().toISOString(),profile,prefs,items},null,2)],{type:"application/json"}),url=URL.createObjectURL(blob),a=document.createElement("a");a.href=url;a.download=`birthday-calendar-backup-${new Date().toISOString().slice(0,10)}.json`;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);toast(tr().exported)}
async function importBackup(file){try{const data=JSON.parse(await file.text());if(!data||!Array.isArray(data.items))throw 0;items=data.items;profile=data.profile||profile;prefs={...prefs,...data.prefs};saveItems();savePrefs();localStorage.setItem(PROFILE,JSON.stringify(profile));applyTheme();translate();toast(tr().imported)}catch{toast(tr().invalidBackup)}}
$$('[data-lang]').forEach(b=>b.onclick=()=>{prefs.lang=b.dataset.lang;savePrefs();translate();updateZodiacField()});$$('[data-view]').forEach(b=>b.onclick=()=>{$$('[data-view]').forEach(x=>x.classList.toggle("active",x===b));$$('.view-panel').forEach(x=>x.classList.remove("active"));$(`#${b.dataset.view}View`).classList.add("active")});
$("#openAdd").onclick=()=>openPerson();$("#openProfile").onclick=openProfile;$("#openSettings").onclick=()=>{$("#themeSelect").value=prefs.theme;updateProfileUI();$("#settingsDialog").showModal()};$("#editProfile").onclick=openProfile;$("#toggleFilters").onclick=()=>$("#filterRow").hidden=!$("#filterRow").hidden;$("#searchInput").oninput=renderList;$("#addAllCalendar").onclick=()=>downloadCalendar(items);
$("#personPhoto").onchange=async e=>{if(!e.target.files[0])return;try{pendingPhoto=await processPhoto(e.target.files[0]);renderPhoto()}catch{toast(tr().photoError)}};
$("#personDate").oninput=updateZodiacField;
$("#cancelBirthday").onclick=()=>$("#birthdayDialog").close();
$("#birthdayForm").onsubmit=e=>{e.preventDefault();if(isPublicView)return;const id=$("#personId").value,previous=items.find(x=>x.id===id),record=normalizeItem({...previous,id:id||crypto.randomUUID(),name:$("#personName").value.trim(),date:$("#personDate").value,eventType:$("#personEventType").value,relation,phone:$("#personPhone").value.trim(),interests:$("#personInterests").value.trim(),personality:$("#personPersonality").value.trim(),style:$("#personStyle").value.trim(),wishlist:$("#personWishlist").value.trim(),gift:$("#personGift").value.trim(),budget:Number($("#personBudget").value)||0,note:$("#personNote").value.trim(),photo:pendingPhoto});if(!record.name||!record.date)return;id?items=items.map(x=>x.id===id?record:x):items.push(record);saveItems();$("#birthdayDialog").close();renderAll();toast(tr().saved)};
$("#copyGreeting").onclick=async()=>{await navigator.clipboard.writeText($("#greetingText").value);toast(tr().copied)};$("#shareWhatsapp").onclick=()=>shareUrl("whatsapp");$("#shareTelegram").onclick=()=>shareUrl("telegram");$("#nativeShare").onclick=()=>navigator.share?.({text:$("#greetingText").value}).catch(()=>{});
$("#profileMode").onchange=updateModeHint;$("#profileForm").onsubmit=e=>{e.preventDefault();if(isPublicView)return;const mode=$("#profileMode").value;if(mode==="public"&&!currentUser){toast(tr().needAccountForPublic);openAuth("login");return}profile={name:$("#ownerName").value.trim(),currency:$("#ownerCurrency").value,mode};localStorage.setItem(PROFILE,JSON.stringify(profile));queueCloudSave();$("#profileDialog").close();translate();toast(tr().saved)};
$("#signOutButton").onclick=async()=>{await AppAuth.signOutUser();localStorage.setItem(GUEST,"1");if(profile){profile.mode="private";localStorage.setItem(PROFILE,JSON.stringify(profile))}updateProfileUI();toast(tr().signedOut)};
$("#copyShareLink").onclick=async()=>{await navigator.clipboard.writeText($("#shareLinkInput").value);toast(tr().linkCopied)};
function openAuth(mode="login"){authMode=mode;renderAuthTabs();$("#authError").hidden=true;if(!$("#authDialog").open)$("#authDialog").showModal()}
function renderAuthTabs(){$$('[data-authtab]').forEach(b=>b.classList.toggle("active",b.dataset.authtab===authMode));$("#authConfirmRow").hidden=authMode!=="signup";$("#authSubmit").textContent=authMode==="signup"?tr().signupAction:tr().loginAction;$("#authPassword").autocomplete=authMode==="signup"?"new-password":"current-password"}
function authErrorMessage(code){return tr().authErrors[code]||tr().authErrors.default}
$$('[data-authtab]').forEach(b=>b.onclick=()=>{authMode=b.dataset.authtab;renderAuthTabs()});
$("#authForm").onsubmit=async e=>{e.preventDefault();const email=$("#authEmail").value.trim(),pass=$("#authPassword").value,confirm=$("#authPasswordConfirm").value;$("#authError").hidden=true;if(authMode==="signup"&&pass!==confirm){$("#authError").textContent=tr().passwordMismatch;$("#authError").hidden=false;return}try{if(authMode==="signup")await AppAuth.signUp(email,pass);else await AppAuth.signIn(email,pass)}catch(err){$("#authError").textContent=authErrorMessage(err.code);$("#authError").hidden=false}};
$("#forgotPassword").onclick=async()=>{const email=$("#authEmail").value.trim();if(!email){$("#authError").textContent=tr().enterEmailFirst;$("#authError").hidden=false;return}try{await AppAuth.resetPassword(email);toast(tr().resetSent)}catch(err){$("#authError").textContent=authErrorMessage(err.code);$("#authError").hidden=false}};
function leaveAuthAsGuest(){localStorage.setItem(GUEST,"1");if($("#authDialog").open)$("#authDialog").close();if(!profile)setTimeout(()=>$("#profileDialog").showModal(),200)}
$("#continueGuest").onclick=leaveAuthAsGuest;$("#authClose").onclick=leaveAuthAsGuest;$("#authDialog").addEventListener("cancel",()=>localStorage.setItem(GUEST,"1"));
$("#openAuth")?.addEventListener("click",()=>openAuth("login"));
$("#themeSelect").onchange=e=>{prefs.theme=e.target.value;savePrefs();applyTheme()};$("#exportData").onclick=exportBackup;$("#importData").onchange=e=>!isPublicView&&e.target.files[0]&&importBackup(e.target.files[0]);matchMedia("(prefers-color-scheme: light)").addEventListener?.("change",()=>prefs.theme==="auto"&&applyTheme());
async function syncFromCloud(uid){try{const cloud=await AppCloud.loadUserData(uid);if(cloud){items=Array.isArray(cloud.items)?cloud.items.map(normalizeItem):items;profile=cloud.profile||profile;prefs={...prefs,...(cloud.prefs||{})};localStorage.setItem(STORE,JSON.stringify(items));savePrefs();if(profile)localStorage.setItem(PROFILE,JSON.stringify(profile))}else{await AppCloud.saveUserData(uid,{profile,prefs,items});if(profile?.mode==="public")await AppCloud.setPublicShare(uid,publicPayload())}}catch(err){console.warn("Cloud sync failed",err)}applyTheme();translate();window.dispatchEvent(new CustomEvent("birthday-data-changed"));if(!profile)setTimeout(()=>$("#profileDialog").showModal(),300)}
function handleAuthChange(user){currentUser=user;updateProfileUI();if(user){if($("#authDialog").open)$("#authDialog").close();localStorage.removeItem(GUEST);syncFromCloud(user.uid)}else if(!wishlistParam){const guest=localStorage.getItem(GUEST);if(!guest&&!profile)openAuth("login");else if(!profile)setTimeout(()=>$("#profileDialog").showModal(),350)}}
async function initPublicView(){document.body.classList.add("public-view");$("#openProfile").disabled=true;applyTheme();const data=await AppCloud.loadPublicShare(shareParam);const banner=$("#publicBanner");if(!data){banner.hidden=false;translate();banner.textContent=tr().publicUnavailable;return}items=Array.isArray(data.items)?data.items.map(normalizeItem):[];profile={name:data.name,currency:data.currency,mode:"public"};translate();window.dispatchEvent(new CustomEvent("birthday-data-changed"));banner.hidden=false;banner.textContent=`${tr().publicBannerViewing} ${data.name}`}
function updateItem(id,patch){items=items.map(x=>x.id===id?normalizeItem({...x,...patch}):x);saveItems();renderAll();window.dispatchEvent(new CustomEvent("birthday-data-changed"))}
function addItems(records){const known=new Set(items.map(x=>`${x.name.toLowerCase()}|${x.date}`));records.map(normalizeItem).forEach(x=>{if(x.name&&x.date&&!known.has(`${x.name.toLowerCase()}|${x.date}`)){items.push(x);known.add(`${x.name.toLowerCase()}|${x.date}`)}});saveItems();renderAll();window.dispatchEvent(new CustomEvent("birthday-data-changed"))}
window.BirthdayApp={getState:()=>({items:structuredClone(items),profile:profile?structuredClone(profile):null,lang:prefs.lang,user:currentUser?{uid:currentUser.uid,email:currentUser.email}:null}),getItem:id=>items.find(x=>x.id===id),updateItem,addItems,setPendingPhoto:value=>{pendingPhoto=value;renderPhoto()},notify:toast,openAuth:()=>openAuth("login"),openPerson};
if(isPublicView){initPublicView()}else{applyTheme();translate();AppAuth.onChange(handleAuthChange);if(profile&&new URLSearchParams(location.search).get("action")==="add")setTimeout(()=>openPerson(),150)}
})();
