"use client";

import { FormEvent, useEffect, useMemo, useState } from "react";
import { Bell, CakeSlice, CalendarDays, CalendarPlus, Download, Gift, Plus, Search, Sparkles, Trash2, Users } from "lucide-react";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Dialog, DialogContent, DialogDescription, DialogFooter, DialogHeader, DialogTitle } from "@/components/ui/dialog";

type Birthday={id:string;name:string;date:string;relation:string;note?:string};
type Lang="ru"|"ro";
const STORAGE_KEY="birthday-calendar-ru-v1",LANG_KEY="birthday-calendar-lang";
const copy={
 ru:{assistant:"Личный помощник",titleA:"Календарь",titleB:"дней рождения",total:"дней рождения",month:"в этом месяце",today:"сегодня",calendar:"Календарь iPhone",alerts:"Ежегодно · уведомления за 7 и 1 день",addAll:"Добавить все",nearest:"Ближайший праздник",emptyTitle:"Здесь появится ближайший праздник",emptyText:"Добавьте первый день рождения, чтобы ничего не забыть.",add:"Добавить",dates:"Все важные даты",birthdays:"Дни рождения",search:"Найти человека",addTitle:"🎁 Добавить день рождения",addDescription:"Заполните данные — дата сохранится на этом iPhone.",name:"Имя",nameExample:"Например, Татьяна",birthDate:"Дата рождения",relationQuestion:"Кем вам приходится этот человек?",note:"Заметка",optional:"необязательно",noteExample:"Интересы или идея подарка",save:"Сохранить",deleteAsk:"Удалить этот день рождения?",years:"лет",todayLabel:"Сегодня",tomorrow:"Завтра",inPrefix:"через",day1:"день",day2:"дня",day5:"дней",birthdayFor:"День рождения",weekAlert:"Через неделю день рождения",dayAlert:"Завтра день рождения",relations:{family:"Семья",friend:"Друг",colleague:"Коллега",partner:"Партнёр",other:"Другое"}},
 ro:{assistant:"Asistent personal",titleA:"Calendarul",titleB:"zilelor de naștere",total:"zile de naștere",month:"în această lună",today:"astăzi",calendar:"Calendar iPhone",alerts:"Anual · alerte cu 7 zile și 1 zi înainte",addAll:"Adaugă toate",nearest:"Cea mai apropiată aniversare",emptyTitle:"Aici va apărea următoarea aniversare",emptyText:"Adaugă prima zi de naștere ca să nu uiți nimic.",add:"Adaugă",dates:"Toate datele importante",birthdays:"Zile de naștere",search:"Caută o persoană",addTitle:"🎁 Adaugă o zi de naștere",addDescription:"Completează datele — acestea se păstrează pe acest iPhone.",name:"Nume",nameExample:"De exemplu, Tatiana",birthDate:"Data nașterii",relationQuestion:"Ce relație ai cu această persoană?",note:"Notiță",optional:"opțional",noteExample:"Interese sau idee de cadou",save:"Salvează",deleteAsk:"Ștergi această zi de naștere?",years:"ani",todayLabel:"Astăzi",tomorrow:"Mâine",inPrefix:"peste",day1:"zi",day2:"zile",day5:"zile",birthdayFor:"Ziua de naștere",weekAlert:"Peste o săptămână este ziua de naștere",dayAlert:"Mâine este ziua de naștere",relations:{family:"Familie",friend:"Prieten",colleague:"Coleg",partner:"Partener",other:"Altă relație"}}
};
const relationKeys=["family","friend","colleague","partner","other"] as const;
const relationIcons:Record<string,string>={family:"👨‍👩‍👧‍👦",friend:"🤝",colleague:"💼",partner:"❤️",other:"👤"};
const legacy:Record<string,string>={"Семья":"family","Друг":"friend","Коллега":"colleague","Партнёр":"partner","Другое":"other","Familie":"family","Prieten":"friend","Coleg":"colleague","Partener":"partner","Altă relație":"other"};
const relationKey=(value:string)=>legacy[value]||value;
function dateParts(value:string){const [year,month,day]=value.split("-").map(Number);return{year,month,day}}
function nextBirthday(value:string,now=new Date()){const{year,month,day}=dateParts(value),today=new Date(now.getFullYear(),now.getMonth(),now.getDate());let next=new Date(now.getFullYear(),month-1,day);if(next<today)next=new Date(now.getFullYear()+1,month-1,day);return{days:Math.round((next.getTime()-today.getTime())/86400000),age:next.getFullYear()-year}}
function formatDate(value:string,lang:Lang){const{year,month,day}=dateParts(value);return new Intl.DateTimeFormat(lang==="ru"?"ru-RU":"ro-RO",{day:"2-digit",month:"long",year:"numeric"}).format(new Date(year,month-1,day))}
function dayLabel(days:number,lang:Lang){const t=copy[lang];if(days===0)return t.todayLabel;if(days===1)return t.tomorrow;const a=days%10,b=days%100,n=lang==="ro"?(days===1?t.day1:t.day2):(a===1&&b!==11?t.day1:a>=2&&a<=4&&!(b>=12&&b<=14)?t.day2:t.day5);return`${t.inPrefix} ${days} ${n}`}
function icsEscape(value:string){return value.replace(/\\/g,"\\\\").replace(/\n/g,"\\n").replace(/,/g,"\\,").replace(/;/g,"\\;")}
function calendarEvent(item:Birthday,lang:Lang){const t=copy[lang],{year,month,day}=dateParts(item.date),start=`${year}${String(month).padStart(2,"0")}${String(day).padStart(2,"0")}`,tomorrow=new Date(year,month-1,day+1),end=`${tomorrow.getFullYear()}${String(tomorrow.getMonth()+1).padStart(2,"0")}${String(tomorrow.getDate()).padStart(2,"0")}`,rel=t.relations[relationKey(item.relation) as keyof typeof t.relations]||item.relation,description=[rel,item.note].filter(Boolean).join(" · ");return["BEGIN:VEVENT",`UID:birthday-${item.id}@birthday-calendar`,`DTSTART;VALUE=DATE:${start}`,`DTEND;VALUE=DATE:${end}`,"RRULE:FREQ=YEARLY",`SUMMARY:${icsEscape(`🎂 ${t.birthdayFor} — ${item.name}`)}`,`DESCRIPTION:${icsEscape(description)}`,"BEGIN:VALARM","TRIGGER:-P7D","ACTION:DISPLAY",`DESCRIPTION:${icsEscape(`${t.weekAlert} — ${item.name}`)}`,"END:VALARM","BEGIN:VALARM","TRIGGER:-P1D","ACTION:DISPLAY",`DESCRIPTION:${icsEscape(`${t.dayAlert} — ${item.name}`)}`,"END:VALARM","END:VEVENT"].join("\r\n")}

export default function Home(){
 const[items,setItems]=useState<Birthday[]>([]),[loaded,setLoaded]=useState(false),[open,setOpen]=useState(false),[query,setQuery]=useState(""),[lang,setLang]=useState<Lang>("ru");
 const[name,setName]=useState(""),[date,setDate]=useState(""),[relation,setRelation]=useState("family"),[note,setNote]=useState("");const t=copy[lang];
 useEffect(()=>{try{const saved=localStorage.getItem(STORAGE_KEY),savedLang=localStorage.getItem(LANG_KEY) as Lang|null;if(saved)setItems(JSON.parse(saved));if(savedLang==="ro"||savedLang==="ru")setLang(savedLang)}catch{}setLoaded(true);if(new URLSearchParams(window.location.search).get("action")==="add")setOpen(true)},[]);
 useEffect(()=>{if(loaded){localStorage.setItem(STORAGE_KEY,JSON.stringify(items));localStorage.setItem(LANG_KEY,lang);document.documentElement.lang=lang}},[items,lang,loaded]);
 const sorted=useMemo(()=>[...items].filter(x=>x.name.toLowerCase().includes(query.toLowerCase())).sort((a,b)=>nextBirthday(a.date).days-nextBirthday(b.date).days),[items,query]);
 const today=sorted.filter(x=>nextBirthday(x.date).days===0),thisMonth=sorted.filter(x=>dateParts(x.date).month===new Date().getMonth()+1),nearest=sorted[0];
 function addBirthday(e:FormEvent){e.preventDefault();if(!name.trim()||!date)return;setItems(x=>[...x,{id:crypto.randomUUID(),name:name.trim(),date,relation,note:note.trim()}]);setName("");setDate("");setRelation("family");setNote("");setOpen(false)}
 function removeBirthday(id:string){if(confirm(t.deleteAsk))setItems(x=>x.filter(i=>i.id!==id))}
 function addToCalendar(selected:Birthday[]){if(!selected.length)return;const body=["BEGIN:VCALENDAR","VERSION:2.0","PRODID:-//Birthday Calendar//RO-RU","CALSCALE:GREGORIAN","METHOD:PUBLISH",...selected.map(x=>calendarEvent(x,lang)),"END:VCALENDAR"].join("\r\n"),url=URL.createObjectURL(new Blob([body],{type:"text/calendar;charset=utf-8"})),link=document.createElement("a");link.href=url;link.download=selected.length===1?`birthday-${selected[0].name}.ics`:"birthdays.ics";document.body.appendChild(link);link.click();link.remove();setTimeout(()=>URL.revokeObjectURL(url),1000)}
 return <main className="birthday-shell"><div className="aurora aurora-one"/><div className="aurora aurora-two"/><div className="aurora aurora-three"/><div className="app-frame">
  <header className="topbar"><div className="brand-mark"><CakeSlice size={25}/></div><div><p className="eyebrow">{t.assistant}</p><h1>{t.titleA}<br/>{t.titleB}</h1></div><div className="header-actions"><div className={`language-slider ${lang}`} role="group" aria-label="Language / Язык"><span/><button className={lang==="ro"?"active":""} onClick={()=>setLang("ro")}>RO</button><button className={lang==="ru"?"active":""} onClick={()=>setLang("ru")}>RU</button></div><Button aria-label={t.addTitle} className="add-button" size="icon" onClick={()=>setOpen(true)}><Plus/></Button></div></header>
  <section className="summary-grid"><div className="stat-card liquid"><Users/><strong>{items.length}</strong><span>{t.total}</span></div><div className="stat-card liquid"><CalendarDays/><strong>{thisMonth.length}</strong><span>{t.month}</span></div><div className="stat-card accent liquid"><Bell/><strong>{today.length}</strong><span>{t.today}</span></div></section>
  <section className="calendar-sync liquid"><div className="sync-icon"><CalendarPlus/></div><div><strong>{t.calendar}</strong><span>{t.alerts}</span></div><Button disabled={!items.length} onClick={()=>addToCalendar(items)}><Download/> {t.addAll}</Button></section>
  {nearest?<section className="spotlight liquid"><div className="spotlight-top"><span><Sparkles size={14}/> {t.nearest}</span><b>{dayLabel(nextBirthday(nearest.date).days,lang)}</b></div><div className="spotlight-main"><div className="avatar">{nearest.name.slice(0,1).toUpperCase()}</div><div className="spotlight-copy"><h2>{nearest.name}</h2><p>🎂 {formatDate(nearest.date,lang)} · {nextBirthday(nearest.date).age} {t.years}</p></div><div className="age-ring"><strong>{nextBirthday(nearest.date).age}</strong><small>{t.years}</small></div></div></section>:<section className="empty-hero liquid"><Gift/><h2>{t.emptyTitle}</h2><p>{t.emptyText}</p><Button onClick={()=>setOpen(true)}><Plus/> {t.add}</Button></section>}
  <section className="list-section"><div className="section-heading"><div><p className="eyebrow">{t.dates}</p><h2>{t.birthdays}</h2></div>{items.length>3&&<span>{items.length}</span>}</div>{items.length>3&&<label className="search liquid"><Search size={18}/><Input aria-label={t.search} placeholder={t.search} value={query} onChange={e=>setQuery(e.target.value)}/></label>}<div className="birthday-list">{sorted.map(item=>{const info=nextBirthday(item.date),key=relationKey(item.relation),rel=t.relations[key as keyof typeof t.relations]||item.relation;return <article className={`${info.days===0?"birthday-row today":"birthday-row"} liquid`} key={item.id}><div className="mini-avatar">{relationIcons[key]||"👤"}</div><div className="person"><h3>{item.name}</h3><p>🎂 {formatDate(item.date,lang)} · {info.age} {t.years}</p><span>{rel}{item.note?` · ${item.note}`:""}</span></div><div className="when"><b>{dayLabel(info.days,lang)}</b><div className="row-actions"><button aria-label={t.calendar} onClick={()=>addToCalendar([item])}><CalendarPlus/></button><button aria-label={t.deleteAsk} onClick={()=>removeBirthday(item.id)}><Trash2/></button></div></div></article>})}</div></section>
 </div><Dialog open={open} onOpenChange={setOpen}><DialogContent className="birthday-dialog liquid"><DialogHeader><DialogTitle>{t.addTitle}</DialogTitle><DialogDescription>{t.addDescription}</DialogDescription></DialogHeader><form id="birthday-form" className="birthday-form" onSubmit={addBirthday}><label>{t.name}<Input autoFocus required placeholder={t.nameExample} value={name} onChange={e=>setName(e.target.value)}/></label><label>{t.birthDate}<Input required type="date" value={date} onChange={e=>setDate(e.target.value)}/></label><fieldset><legend>{t.relationQuestion}</legend><div className="relation-grid">{relationKeys.map(key=><button className={relation===key?"selected":""} type="button" key={key} onClick={()=>setRelation(key)}><span>{relationIcons[key]}</span>{t.relations[key]}</button>)}</div></fieldset><label>{t.note} <em>{t.optional}</em><Input placeholder={t.noteExample} value={note} onChange={e=>setNote(e.target.value)}/></label></form><DialogFooter><Button className="save-button" form="birthday-form" type="submit"><CakeSlice/> {t.save}</Button></DialogFooter></DialogContent></Dialog>
 </main>
}
